[settings]
enable_tracing = false

[relaychain]
default_image = "docker.io/parity/polkadot:v0.9.22"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 2000
cumulus_based = true

  [parachains.collator]
  name = "collator01"
  image = "localhost:5000/parachain-template-node"
  command = "parachain-template-node"
  args = ["-lparachain=debug"]
